EXCEL_FILE_NAMES = [
    "african_country_GDP_data",
    "country_code_data",
    "distribution_of_population_between_different_poverty_thresholds_up_to_30_dollars",
    "life_expectancy",
]

COUNTIES_DICT = dict(
    COM="Comoros",
    CPV="Cabo Verde",
    DJI="Djibouti",
    DZA="Algeria",
    EGY="Egypt",
    ERI="Eritrea",
    ETH="Ethiopia",
    GAB="Gabon",
    GHA="Ghana",
    GIN="Guinea",
    GMB="Gambia",
    GNB="Guinea-Bissau",
    GNQ="Equatorial Guinea",
    KEN="Kenya",
    LBR="Liberia",
    LBY="Libya",
    LSO="Lesotho",
    MAR="Morocco",
    MDG="Madagascar",
    MLI="Mali",
    MOZ="Mozambique",
    MRT="Mauritania",
    MUS="Mauritius",
    MWI="Malawi",
    NAM="Namibia",
    NER="Niger",
    NGA="Nigeria",
    RWA="Rwanda",
    SDN="Sudan",
    SEN="Senegal",
    SLE="Sierra Leone",
    SOM="Somalia",
    SSD="South Sudan",
    STP="Sao Tome & Principe",
    SWZ="Eswatini",
    SYC="Seychelles",
    TCD="Chad",
    TGO="Togo",
    TUN="Tunisia",
    TZA="Tanzania",
    UGA="Uganda",
    ZAF="South Africa",
    ZMB="Zambia",
    ZWE="Zimbabwe",
)

COUNTRY_CODE = [
    "DZA",
    "AGO",
    "BEN",
    "BWA",
    "BFA",
    "BDI",
    "CMR",
    "CPV",
    "CAF",
    "TCD",
    "COM",
    "COG",
    "CIV",
    "COD",
    "DJI",
    "EGY",
    "GNQ",
    "ERI",
    "SWZ",
    "ETH",
    "GAB",
    "GMB",
    "GHA",
    "GIN",
    "GNB",
    "KEN",
    "LSO",
    "LBR",
    "LBY",
    "MDG",
    "MWI",
    "MLI",
    "MRT",
    "MUS",
    "MAR",
    "MOZ",
    "NAM",
    "NER",
    "NGA",
    "RWA",
    "STP",
    "SEN",
    "SYC",
    "SLE",
    "SOM",
    "ZAF",
    "SSD",
    "SDN",
    "TZA",
    "TGO",
    "TUN",
    "UGA",
    "ZMB",
    "ZWE",
]


REGION = [
    "Middle Africa",
    "Eastern Africa",
    "Western Africa",
    "Southern Africa",
    "Northern Africa",
]
